dynamixel_controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

  leg_0_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - body_leg_0
      - leg_0_1_2
      - leg_0_2_3

  leg_1_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - body_leg_1
      - leg_1_1_2
      - leg_1_2_3

  leg_2_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - body_leg_2
      - leg_2_1_2
      - leg_2_2_3

  leg_3_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - body_leg_3
      - leg_3_1_2
      - leg_3_2_3

  leg_4_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - body_leg_4
      - leg_4_1_2
      - leg_4_2_3

  leg_5_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - body_leg_5
      - leg_5_1_2
      - leg_5_2_3

dynamixel_control:
  loop_frequency: 100
  cycle_time_error_threshold: 0.1
  baudrate: 115200 # in bauds
  read_timeout: 0.05 # in seconds
  scan_timeout: 1 # in seconds

  # correspondance between hardware IDs of the actuators and their names in ROS
  default_command_interface: position
  servos:
    body_leg_0:
      id: 7
    leg_0_1_2:
      id: 8
    leg_0_2_3:
      id: 9
    body_leg_1:
      id: 4
    leg_1_1_2:
      id: 5
    leg_1_2_3:
      id: 6
    body_leg_2:
      id: 1
    leg_2_1_2:
      id: 2
    leg_2_2_3:
      id: 3
    body_leg_3:
      id: 16
    leg_3_1_2:
      id: 17
    leg_3_2_3:
      id: 18
    body_leg_4:
     id: 13
    leg_4_1_2:
     id: 14
    leg_4_2_3:
     id: 15
    body_leg_5:
      id: 10
    leg_5_1_2:
      id: 11
    leg_5_2_3:
      id: 12
