dynamixel_control:
  # serial_interface: /dev/usb2ax6
  serial_interface: /dev/ttyACM0

  servos:
    body_leg_0:
      offset: 2.74889357189
    leg_0_1_2:
      offset: 3.14159265359
    leg_0_2_3:
      offset: 3.14159265359
    body_leg_1:
      offset: 3.14159265359
    leg_1_1_2:
      offset: 3.14159265359
    leg_1_2_3:
      offset: 3.14159265359
    body_leg_2:
      offset: 3.53429173529
    leg_2_1_2:
      offset: 3.14159265359
    leg_2_2_3:
      offset: 3.14159265359
    body_leg_3:
      offset: 2.74889357189
    leg_3_1_2:
      offset: 3.14159265359
    leg_3_2_3:
      offset: 3.14159265359
    body_leg_4:
      offset: 3.14159265359
    leg_4_1_2:
      offset: 3.14159265359
    leg_4_2_3:
      offset: 3.14159265359
    body_leg_5:
      offset: 3.53429173529
    leg_5_1_2:
      offset: 3.14159265359
    leg_5_2_3:
      offset: 3.14159265359
